-- ==========================================
-- MASTER RESET SCRIPT - EasyEmpaque
-- ==========================================
-- Este script borra TODAS las tablas y las recrea 
-- con el esquema actual necesario para que la app funcione.
-- ==========================================

-- 1. LIMPIEZA TOTAL (Borrar todo para empezar de cero)
DROP TABLE IF EXISTS ventas_detalles CASCADE;
DROP TABLE IF EXISTS ventas_comprobantes CASCADE;
DROP TABLE IF EXISTS gastos_lote CASCADE;
DROP TABLE IF EXISTS lotes_ingreso CASCADE;
DROP TABLE IF EXISTS movimientos_cuenta CASCADE;
DROP TABLE IF EXISTS plantilla_productos CASCADE;
DROP TABLE IF EXISTS conceptos_gastos CASCADE;
DROP TABLE IF EXISTS envases CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS quinteros CASCADE;

-- 2. CREACIÓN DE TABLAS MAESTRAS
CREATE TABLE quinteros (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    telefono VARCHAR(50),
    estado VARCHAR(20) DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

CREATE TABLE clientes (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    mercado VARCHAR(255),
    telefono VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

CREATE TABLE envases (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    capacidad_kg NUMERIC(10,2),
    equivalencia_bulto NUMERIC(5,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

CREATE TABLE conceptos_gastos (
    id SERIAL PRIMARY KEY,
    descripcion VARCHAR(255) NOT NULL,
    monto_actual NUMERIC(15,2) NOT NULL,
    tipo_envase VARCHAR(100) DEFAULT 'Torito',
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. PROCESO OPERATIVO (Lotes y Ventas)
CREATE TABLE lotes_ingreso (
    id SERIAL PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    quintero_id INTEGER REFERENCES quinteros(id) ON DELETE RESTRICT,
    producto TEXT NOT NULL DEFAULT 'Sin Especificar',
    estado VARCHAR(20) DEFAULT 'abierto' CHECK (estado IN ('abierto', 'liquidado')),
    rasos_comprados INTEGER NOT NULL DEFAULT 0,
    rasos_descarte INTEGER NOT NULL DEFAULT 0,
    toritos_obtenidos INTEGER NOT NULL DEFAULT 0,
    precio_final_pagado NUMERIC(15,2) DEFAULT NULL,
    precio_pagado_por_bulto NUMERIC(10,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

CREATE TABLE gastos_lote (
    id SERIAL PRIMARY KEY,
    lote_id INTEGER REFERENCES lotes_ingreso(id) ON DELETE CASCADE,
    concepto VARCHAR(255) NOT NULL,
    monto_congelado NUMERIC(15,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

CREATE TABLE ventas_comprobantes (
    id SERIAL PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    cliente_id INTEGER REFERENCES clientes(id) ON DELETE RESTRICT,
    gastos_transporte_bajada NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_bruto NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_neto NUMERIC(15,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

CREATE TABLE ventas_detalles (
    id SERIAL PRIMARY KEY,
    comprobante_id INTEGER REFERENCES ventas_comprobantes(id) ON DELETE CASCADE,
    lote_id INTEGER REFERENCES lotes_ingreso(id) ON DELETE RESTRICT,
    envase_id INTEGER REFERENCES envases(id) ON DELETE RESTRICT,
    producto TEXT NOT NULL DEFAULT 'Sin Especificar',
    calibre TEXT,
    cantidad INTEGER NOT NULL,
    precio_unitario_bruto NUMERIC(15,2) NOT NULL,
    precio_unitario_neto NUMERIC(15,2) NOT NULL,
    descuento_aplicado NUMERIC(15,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 4. AUXILIARES Y CUENTAS
CREATE TABLE plantilla_productos (
    id SERIAL PRIMARY KEY,
    orden INTEGER NOT NULL,
    envase_nombre TEXT NOT NULL,
    producto TEXT NOT NULL,
    calibre TEXT,
    bg_color TEXT DEFAULT 'bg-white',
    text_color TEXT DEFAULT 'text-gray-900'
);

CREATE TABLE movimientos_cuenta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    tipo_entidad TEXT NOT NULL CHECK (tipo_entidad IN ('quintero', 'cliente')),
    entidad_id BIGINT NOT NULL,
    comprobante_relacionado_id BIGINT,
    detalle TEXT NOT NULL,
    tipo_movimiento TEXT NOT NULL CHECK (tipo_movimiento IN ('liquidacion', 'pago', 'venta', 'cobro')),
    monto NUMERIC(15, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. SEGURIDAD (RLS)
ALTER TABLE quinteros ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE envases ENABLE ROW LEVEL SECURITY;
ALTER TABLE conceptos_gastos ENABLE ROW LEVEL SECURITY;
ALTER TABLE lotes_ingreso ENABLE ROW LEVEL SECURITY;
ALTER TABLE gastos_lote ENABLE ROW LEVEL SECURITY;
ALTER TABLE ventas_comprobantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE ventas_detalles ENABLE ROW LEVEL SECURITY;
ALTER TABLE plantilla_productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos_cuenta ENABLE ROW LEVEL SECURITY;

-- Políticas permisivas para rol 'anon'
CREATE POLICY "Permitir_todo_anon_quinteros" ON quinteros FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_todo_anon_clientes" ON clientes FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_todo_anon_envases" ON envases FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_todo_anon_conceptos_gastos" ON conceptos_gastos FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_todo_anon_lotes_ingreso" ON lotes_ingreso FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_todo_anon_gastos_lote" ON gastos_lote FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_todo_anon_ventas_comprobantes" ON ventas_comprobantes FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_todo_anon_ventas_detalles" ON ventas_detalles FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_todo_anon_plantilla" ON plantilla_productos FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_todo_anon_movimientos" ON movimientos_cuenta FOR ALL TO anon USING (true) WITH CHECK (true);

-- 6. DATOS INICIALES (Catálogos)
INSERT INTO envases (nombre, capacidad_kg, equivalencia_bulto) VALUES
('Torito', 18, 1.0),
('Bandeja Cherry', 0, 0.33),
('Raso', 24, 1.0)
ON CONFLICT DO NOTHING;

INSERT INTO conceptos_gastos (descripcion, monto_actual, tipo_envase) VALUES
('Cajón', 1300, 'Torito'),
('Embalado', 800, 'Torito'),
('Papel', 100, 'Torito'),
('Recinita', 100, 'Torito'),
('Palet', 100, 'Torito'),
('Suncho', 100, 'Torito'),
('Raclador', 300, 'Torito'),
('Carga', 110, 'Torito'),
-- Copia para Jaulita
('Cajón', 1300, 'Jaulita'),
('Embalado', 800, 'Jaulita'),
('Papel', 100, 'Jaulita'),
('Recinita', 100, 'Jaulita'),
('Palet', 100, 'Jaulita'),
('Suncho', 100, 'Jaulita'),
('Raclador', 300, 'Jaulita'),
('Carga', 110, 'Jaulita'),
-- Copia para Bandeja
('Cajón', 1300, 'Bandeja'),
('Embalado', 800, 'Bandeja'),
('Papel', 100, 'Bandeja'),
('Recinita', 100, 'Bandeja'),
('Palet', 100, 'Bandeja'),
('Suncho', 100, 'Bandeja'),
('Raclador', 300, 'Bandeja'),
('Carga', 110, 'Bandeja')
ON CONFLICT DO NOTHING;

INSERT INTO plantilla_productos (orden, envase_nombre, producto, calibre, bg_color, text_color) VALUES
(1, 'Torito', 'Tomate', 'Grande', 'bg-red-600', 'text-white'),
(2, 'Torito', 'Tomate', 'Pera', 'bg-red-600', 'text-white'),
(3, 'Torito', 'Tomate', 'Mediano', 'bg-red-600', 'text-white'),
(4, 'Torito', 'Tomate', 'descarte', 'bg-red-600', 'text-white'),
(5, 'Torito', 'Tomate', '2da', 'bg-red-600', 'text-white'),
(6, 'Torito', 'Tomate', 'chicote', 'bg-red-600', 'text-white'),
(7, 'Torito', 'Tomate', 'Tripoli', 'bg-red-600', 'text-white'),
(8, 'Torito', 'Pto Verde', '2 F', 'bg-green-600', 'text-white'),
(9, 'Torito', 'Pto Verde', '2 1/2 F', 'bg-green-600', 'text-white'),
(10, 'Torito', 'Amarillo', '3 F', 'bg-yellow-400', 'text-gray-900'),
(11, 'Torito', 'Pto Veteado', '2 F', 'bg-red-400', 'text-white'),
(12, 'Torito', 'Pto Rojo', '21/2F', 'bg-red-700', 'text-white'),
(13, 'Torito', 'Pto Rojo', '2 F', 'bg-red-700', 'text-white'),
(15, 'Torito', 'chaucha', 'larga', 'bg-lime-400', 'text-gray-900'),
(16, 'Torito', 'chaucha', 'ancha', 'bg-lime-400', 'text-gray-900'),
(17, 'Torito', 'zapallito', '', 'bg-emerald-800', 'text-white'),
(18, 'Torito', 'albahaca', '', 'bg-emerald-200', 'text-gray-900'),
(19, 'Torito', 'pepino', '', 'bg-green-800', 'text-white'),
(20, 'Torito', 'limon', '', 'bg-yellow-300', 'text-gray-900'),
(21, 'Bandeja', 'Cherry', 'Grande', 'bg-white', 'text-red-600');

-- 7. REFRESCAR CACHÉ DE POSTGREST
NOTIFY pgrst, 'reload schema';
